from fastapi import APIRouter

from app.api.v1 import activities, admin, agents, analytics, ai, auth, bi, calendar, companies, contacts, dashboard, deals, developers, documents, emails, integrations, leads, meetings, mobile, notifications, portal, portal_admin, portal_auth, tasks, tenants, users, workflows

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(tenants.router)
api_router.include_router(users.router)
api_router.include_router(leads.router)
api_router.include_router(deals.router)
api_router.include_router(contacts.router)
api_router.include_router(companies.router)
api_router.include_router(activities.router)
api_router.include_router(tasks.router)
api_router.include_router(dashboard.router)
api_router.include_router(analytics.router)
api_router.include_router(bi.router)
api_router.include_router(admin.router)
api_router.include_router(integrations.router)
api_router.include_router(mobile.router)
api_router.include_router(notifications.router)
api_router.include_router(meetings.router)
api_router.include_router(calendar.router)
api_router.include_router(emails.router)
api_router.include_router(emails.tracking_router)
api_router.include_router(workflows.router)
api_router.include_router(documents.router)
api_router.include_router(ai.router)
api_router.include_router(agents.router)
api_router.include_router(developers.router)
api_router.include_router(portal_auth.router)
api_router.include_router(portal.router)
api_router.include_router(portal_admin.router)
