PERMISSIONS = [
    ("tenant", "read", "tenant:read"),
    ("tenant", "write", "tenant:write"),
    ("tenant", "delete", "tenant:delete"),
    ("user", "read", "user:read"),
    ("user", "write", "user:write"),
    ("user", "delete", "user:delete"),
    ("role", "read", "role:read"),
    ("settings", "read", "settings:read"),
    ("settings", "write", "settings:write"),
    ("lead", "read", "lead:read"),
    ("lead", "write", "lead:write"),
    ("lead", "delete", "lead:delete"),
    ("deal", "read", "deal:read"),
    ("deal", "write", "deal:write"),
    ("deal", "delete", "deal:delete"),
    ("contact", "read", "contact:read"),
    ("contact", "write", "contact:write"),
    ("contact", "delete", "contact:delete"),
    ("company", "read", "company:read"),
    ("company", "write", "company:write"),
    ("company", "delete", "company:delete"),
    ("activity", "read", "activity:read"),
    ("activity", "write", "activity:write"),
    ("activity", "delete", "activity:delete"),
    ("task", "read", "task:read"),
    ("task", "write", "task:write"),
    ("task", "delete", "task:delete"),
]

ROLE_PERMISSIONS = {
    "owner": [slug for _, _, slug in PERMISSIONS],
    "admin": [
        "tenant:read",
        "tenant:write",
        "user:read",
        "user:write",
        "user:delete",
        "role:read",
        "settings:read",
        "settings:write",
        "lead:read",
        "lead:write",
        "lead:delete",
        "deal:read",
        "deal:write",
        "deal:delete",
        "contact:read",
        "contact:write",
        "contact:delete",
        "company:read",
        "company:write",
        "company:delete",
        "activity:read",
        "activity:write",
        "activity:delete",
        "task:read",
        "task:write",
        "task:delete",
    ],
    "member": [
        "tenant:read",
        "user:read",
        "role:read",
        "settings:read",
        "lead:read",
        "lead:write",
        "deal:read",
        "deal:write",
        "contact:read",
        "contact:write",
        "company:read",
        "company:write",
        "activity:read",
        "activity:write",
        "task:read",
        "task:write",
    ],
}

SYSTEM_ROLES = [
    ("Owner", "owner"),
    ("Admin", "admin"),
    ("Member", "member"),
]
