PERMISSIONS = [
    ("tenant", "read", "tenant:read"),
    ("tenant", "write", "tenant:write"),
    ("tenant", "delete", "tenant:delete"),
    ("user", "read", "user:read"),
    ("user", "write", "user:write"),
    ("user", "delete", "user:delete"),
    ("role", "read", "role:read"),
    ("settings", "read", "settings:read"),
    ("settings", "write", "settings:write"),
    ("lead", "read", "lead:read"),
    ("lead", "write", "lead:write"),
    ("lead", "delete", "lead:delete"),
    ("deal", "read", "deal:read"),
    ("deal", "write", "deal:write"),
    ("deal", "delete", "deal:delete"),
    ("contact", "read", "contact:read"),
    ("contact", "write", "contact:write"),
    ("contact", "delete", "contact:delete"),
    ("company", "read", "company:read"),
    ("company", "write", "company:write"),
    ("company", "delete", "company:delete"),
    ("activity", "read", "activity:read"),
    ("activity", "write", "activity:write"),
    ("activity", "delete", "activity:delete"),
    ("task", "read", "task:read"),
    ("task", "write", "task:write"),
    ("task", "delete", "task:delete"),
    ("notification", "read", "notification:read"),
    ("notification", "write", "notification:write"),
    ("notification", "delete", "notification:delete"),
    ("meeting", "read", "meeting:read"),
    ("meeting", "write", "meeting:write"),
    ("meeting", "delete", "meeting:delete"),
    ("email", "read", "email:read"),
    ("email", "write", "email:write"),
    ("email", "delete", "email:delete"),
    ("workflow", "read", "workflow:read"),
    ("workflow", "write", "workflow:write"),
    ("workflow", "delete", "workflow:delete"),
    ("document", "read", "document:read"),
    ("document", "write", "document:write"),
    ("document", "delete", "document:delete"),
    ("report", "read", "report:read"),
    ("report", "write", "report:write"),
    ("report", "delete", "report:delete"),
    ("bi", "read", "bi:read"),
    ("bi", "write", "bi:write"),
    ("integration", "read", "integration:read"),
    ("integration", "write", "integration:write"),
    ("integration", "delete", "integration:delete"),
    ("mobile", "read", "mobile:read"),
    ("mobile", "write", "mobile:write"),
    ("admin", "read", "admin:read"),
    ("admin", "write", "admin:write"),
    ("audit", "read", "audit:read"),
    ("security", "read", "security:read"),
    ("security", "write", "security:write"),
    ("session", "read", "session:read"),
    ("session", "write", "session:write"),
    ("role", "write", "role:write"),
    ("agent", "read", "agent:read"),
    ("agent", "write", "agent:write"),
    ("agent", "execute", "agent:execute"),
    ("developer", "read", "developer:read"),
    ("developer", "write", "developer:write"),
    ("support", "read", "support:read"),
    ("support", "write", "support:write"),
    ("support", "delete", "support:delete"),
]

ROLE_PERMISSIONS = {
    "owner": [slug for _, _, slug in PERMISSIONS],
    "admin": [
        "tenant:read",
        "tenant:write",
        "user:read",
        "user:write",
        "user:delete",
        "role:read",
        "settings:read",
        "settings:write",
        "lead:read",
        "lead:write",
        "lead:delete",
        "deal:read",
        "deal:write",
        "deal:delete",
        "contact:read",
        "contact:write",
        "contact:delete",
        "company:read",
        "company:write",
        "company:delete",
        "activity:read",
        "activity:write",
        "activity:delete",
        "task:read",
        "task:write",
        "task:delete",
        "notification:read",
        "notification:write",
        "notification:delete",
        "meeting:read",
        "meeting:write",
        "meeting:delete",
        "email:read",
        "email:write",
        "email:delete",
        "workflow:read",
        "workflow:write",
        "workflow:delete",
        "document:read",
        "document:write",
        "document:delete",
        "report:read",
        "report:write",
        "report:delete",
        "bi:read",
        "bi:write",
        "integration:read",
        "integration:write",
        "integration:delete",
        "mobile:read",
        "mobile:write",
        "admin:read",
        "admin:write",
        "audit:read",
        "security:read",
        "security:write",
        "session:read",
        "session:write",
        "role:write",
        "agent:read",
        "agent:write",
        "agent:execute",
        "developer:read",
        "developer:write",
        "support:read",
        "support:write",
        "support:delete",
    ],
    "member": [
        "tenant:read",
        "user:read",
        "role:read",
        "settings:read",
        "lead:read",
        "lead:write",
        "deal:read",
        "deal:write",
        "contact:read",
        "contact:write",
        "company:read",
        "company:write",
        "activity:read",
        "activity:write",
        "task:read",
        "task:write",
        "notification:read",
        "notification:write",
        "meeting:read",
        "meeting:write",
        "email:read",
        "email:write",
        "workflow:read",
        "document:read",
        "document:write",
        "report:read",
        "bi:read",
        "integration:read",
        "mobile:read",
        "agent:read",
        "agent:execute",
        "developer:read",
        "support:read",
        "support:write",
    ],
}

SYSTEM_ROLES = [
    ("Owner", "owner"),
    ("Admin", "admin"),
    ("Member", "member"),
]
